// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package dbq

import (
	"context"

	"uuid"
)

const deleteEncryptionKeysBySourceHash = `-- name: DeleteEncryptionKeysBySourceHash :exec
WITH deleted_stream_keys AS (
    DELETE FROM stream_encryption_keys WHERE source_hash = $1
    RETURNING source_hash
)
DELETE FROM encryption_keys WHERE hash = $1
`

func (q *Queries) DeleteEncryptionKeysBySourceHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteEncryptionKeysBySourceHash, hash)
	return err
}

const deleteImageCacheEntriesByHash = `-- name: DeleteImageCacheEntriesByHash :exec
DELETE FROM image_cache_entries WHERE hash = $1
`

func (q *Queries) DeleteImageCacheEntriesByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteImageCacheEntriesByHash, hash)
	return err
}

const getLegacyEncryptionKey = `-- name: GetLegacyEncryptionKey :one
SELECT hash, wrapped_key, wrap_nonce, kek_version, kid, scheme, key_uri, created_at FROM encryption_keys WHERE hash = $1
`

func (q *Queries) GetLegacyEncryptionKey(ctx context.Context, hash string) (EncryptionKey, error) {
	row := q.db.QueryRow(ctx, getLegacyEncryptionKey, hash)
	var i EncryptionKey
	err := row.Scan(
		&i.Hash,
		&i.WrappedKey,
		&i.WrapNonce,
		&i.KekVersion,
		&i.Kid,
		&i.Scheme,
		&i.KeyUri,
		&i.CreatedAt,
	)
	return i, err
}

const getStreamEncryptionKey = `-- name: GetStreamEncryptionKey :one
SELECT id, source_hash, asset_type, packaging_type, wrapped_key, wrap_nonce, kek_version, kid, scheme, created_at FROM stream_encryption_keys WHERE id = $1
`

func (q *Queries) GetStreamEncryptionKey(ctx context.Context, id uuid.UUID) (StreamEncryptionKey, error) {
	row := q.db.QueryRow(ctx, getStreamEncryptionKey, id)
	var i StreamEncryptionKey
	err := row.Scan(
		&i.ID,
		&i.SourceHash,
		&i.AssetType,
		&i.PackagingType,
		&i.WrappedKey,
		&i.WrapNonce,
		&i.KekVersion,
		&i.Kid,
		&i.Scheme,
		&i.CreatedAt,
	)
	return i, err
}

const listImageCacheEntriesByHash = `-- name: ListImageCacheEntriesByHash :many
SELECT hash, cache_key, storage_key, created_at FROM image_cache_entries WHERE hash = $1 ORDER BY created_at
`

func (q *Queries) ListImageCacheEntriesByHash(ctx context.Context, hash string) ([]ImageCacheEntry, error) {
	rows, err := q.db.Query(ctx, listImageCacheEntriesByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageCacheEntry{}
	for rows.Next() {
		var i ImageCacheEntry
		if err := rows.Scan(
			&i.Hash,
			&i.CacheKey,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImageCacheEntry = `-- name: UpsertImageCacheEntry :exec
INSERT INTO image_cache_entries (hash, cache_key, storage_key)
VALUES ($1, $2, $3)
ON CONFLICT (hash, storage_key) DO UPDATE SET
	cache_key = EXCLUDED.cache_key,
	created_at = now()
`

type UpsertImageCacheEntryParams struct {
	Hash       string `json:"hash"`
	CacheKey   string `json:"cache_key"`
	StorageKey string `json:"storage_key"`
}

func (q *Queries) UpsertImageCacheEntry(ctx context.Context, arg UpsertImageCacheEntryParams) error {
	_, err := q.db.Exec(ctx, upsertImageCacheEntry, arg.Hash, arg.CacheKey, arg.StorageKey)
	return err
}

const upsertStreamEncryptionKey = `-- name: UpsertStreamEncryptionKey :one
INSERT INTO stream_encryption_keys (id, source_hash, asset_type, packaging_type, wrapped_key, wrap_nonce, kek_version, kid, scheme)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (source_hash, asset_type, packaging_type) DO UPDATE SET
	wrapped_key = EXCLUDED.wrapped_key,
	wrap_nonce = EXCLUDED.wrap_nonce,
	kek_version = EXCLUDED.kek_version,
	kid = EXCLUDED.kid,
	scheme = EXCLUDED.scheme
RETURNING id, source_hash, asset_type, packaging_type, wrapped_key, wrap_nonce, kek_version, kid, scheme, created_at
`

type UpsertStreamEncryptionKeyParams struct {
	ID            uuid.UUID `json:"id"`
	SourceHash    string    `json:"source_hash"`
	AssetType     string    `json:"asset_type"`
	PackagingType string    `json:"packaging_type"`
	WrappedKey    []byte    `json:"wrapped_key"`
	WrapNonce     []byte    `json:"wrap_nonce"`
	KekVersion    string    `json:"kek_version"`
	Kid           string    `json:"kid"`
	Scheme        string    `json:"scheme"`
}

func (q *Queries) UpsertStreamEncryptionKey(ctx context.Context, arg UpsertStreamEncryptionKeyParams) (StreamEncryptionKey, error) {
	row := q.db.QueryRow(ctx, upsertStreamEncryptionKey,
		arg.ID,
		arg.SourceHash,
		arg.AssetType,
		arg.PackagingType,
		arg.WrappedKey,
		arg.WrapNonce,
		arg.KekVersion,
		arg.Kid,
		arg.Scheme,
	)
	var i StreamEncryptionKey
	err := row.Scan(
		&i.ID,
		&i.SourceHash,
		&i.AssetType,
		&i.PackagingType,
		&i.WrappedKey,
		&i.WrapNonce,
		&i.KekVersion,
		&i.Kid,
		&i.Scheme,
		&i.CreatedAt,
	)
	return i, err
}
